name: esm-collections-dev
channels:
  - conda-forge
  - nodefaults
  - ncar
dependencies:
  - jupyterlab>=3
  - xarray
  - dask
  - intake-esm
  - geocat-comp
  - graphviz
  - cf_xarray
  - prefect
  - intake-esm
  - pytest
  - pytest-cov
  - pop-tools
  - metpy
  - xhistogram
  - pip
  - pip:
        - -r requirements.txt
        - git+https://github.com/NCAR/xcollection
