name: cesm-collections-dev
channels:
  - conda-forge
  - nodefaults
  - ncar
dependencies:
  - jupyterlab>=3
  - xarray
  - dask
  - intake-esm
  - geocat-comp
  - cf_xarray
  - prefect
  - intake-esm
  - pytest
  - pip
  - pip:
        - -r requirements.txt
