timeseries:
    mom:
        ydim: yh
        xdim: xh
        horizontal_weights: area_t
        land_sea_mask: wet
        streams:
            - mom6.hm
            - mom6.h_bgc_monthly_z
        variables:
            O2:
                units_in: null
                units_out: mmol / meter^3
                v_min: 1.0
                v_max: 300.0
                log_cbar: True

            PO4:
                units_in: null
                units_out: null
                v_min: 1.0e-2
                v_max: 2.2
                log_cbar: True

            DpCO2:
                units_in: null
                units_out: null
                v_min: -75.0
                v_max: 75.0
                log_cbar: False

            SiO3:
                units_in: null
                units_out: null
                v_min: 0.0
                v_max: 100.0
                log_cbar: True

            NO3:
                units_in: null
                units_out: null
                v_min: 1.0e-2
                v_max: 35.0
                log_cbar: True
                
    pop:
        ydim: nlat
        xdim: nlon
        horizontal_weights: TAREA
        land_sea_mask: KMT
        streams: 
            pop.h:
                vertical_weights: z_t
        variables:
            O2:
                units_in: null
                units_out: mmol / meter^3
                v_min: 1.0
                v_max: 300.0
                log_cbar: True

            PO4:
                units_in: null
                units_out: null
                v_min: 1.0e-2
                v_max: 2.2
                log_cbar: True

            DpCO2:
                units_in: null
                units_out: null
                v_min: -75.0
                v_max: 75.0
                log_cbar: False

            SiO3:
                units_in: null
                units_out: null
                v_min: 0.0
                v_max: 100.0
                log_cbar: True

            NO3:
                units_in: null
                units_out: null
                v_min: 1.0e-2
                v_max: 35.0
                log_cbar: True
                